name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Run a command
        run: echo "Hello, World"

  build_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Build and start containers
        run: |
          docker-compose up -d --build
        working-directory: .

      - name: Lint backend
        run: docker-compose exec -T backend flake8 --config ./app/.flake8

      - name: Lint frontend
        run: docker-compose exec -T frontend npm run lint

      - name: Test backend
        run: docker-compose exec -T backend pytest

      - name: Build frontend
        run: docker-compose exec -T frontend npm run build

      - name: Test frontend
        run: docker-compose exec -T frontend npm test

      - name: Stop Docker Services
        run: docker-compose down
      
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  