name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Run a command
        run: echo "Hello, World"
    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Build docker images
        run: |
          docker-compose up -d --build
      
      - name: List and save images
        run: |
          images=$(docker-compose images -q)
          for image in $images; do
            docker save -o "images/${image}.tar" "$image"
          done
        working-directory: .

      - name: Upload Docker images
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: ./images

      - name: Stop Docker Services
        run: docker-compose down
  
  test_backend:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker images
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Load Docker images
        run: |
          for file in ./images/*.tar; do
            docker load -i "$file"
          done
        working-directory: .

      - name: Run Docker container
        run: |
          docker-compose up -d
        working-directory: .
      
      - name: Run Backend Tests
        run: docker-compose exec -T backend pytest

      - name: Stop Docker Services
        run: docker-compose down

  test_frontend:
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      - name: Download Docker images
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Load Docker images
        run: |
          for file in ./images/*.tar; do
            docker load -i "$file"
          done
        working-directory: .

      - name: Run Docker container
        run: |
          docker-compose up -d
        working-directory: .

      - name: Run Frontend Tests
        run: docker-compose exec -T frontend npm test

      - name: Stop Docker Services
        run: docker-compose down

