name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and Start Docker Services
        run: |
          docker-compose build
          docker-compose up -d

      - name: Wait for Services to Start
        run: sleep 30  # Adjust as needed

      - name: Run Backend Tests
        run: |
          docker-compose exec backend pytest

      - name: Run Frontend Tests
        run: |
          docker-compose exec frontend npm test

      - name: Stop Docker Services
        run: docker-compose down
