name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Start containers
        run: docker-compose up -d --build


    #   - name: Set up Docker Compose
    #     run: |
    #       sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #       sudo chmod +x /usr/local/bin/docker-compose

    #     - name: Build and Start Docker Services
    #     run: |
    #         docker-compose build
    #         docker-compose up

    #     - name: Wait for Services to Start
    #     run: sleep 30  # Adjust as needed

    #     - name: Run Backend Tests
    #     run: |
    #         docker-compose exec backend pytest

    #     - name: Run Frontend Tests
    #     run: |
    #         docker-compose exec frontend npm test

    #     - name: Stop Docker Services
    #     run: docker-compose down
