name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker images
        uses: actions/download-artifact@v3
        with:
          name: .images/docker-images

      - name: Load Docker images
        run: |
          for file in ./images/*.tar; do
            docker load -i "$file"
          done
        working-directory: .

      - name: Run Docker container
        run: |
          docker-compose up -d
        working-directory: .
      
      - name: Run Backend Tests
        run: docker-compose exec -T backend pytest

      - name: Stop Docker Services
        run: docker-compose down
